project:
  type: website

website:
  title: "Jolien Noels"
  site-url: "https://joliennoels.com"
  favicon: assets/imgs/icon.png
  navbar:
    pinned: true
    right:
      - text: Research
        href: research/index.qmd  
      - text: Gallery
        href: gallery.qmd
      - text: Talks
        href: talks.qmd 
      - text: Articles
        href: articles.qmd 
      - text: Code 
        href: https://github.com/JolienNoels?tab=repositories
  back-to-top-navigation: true
  google-analytics: "G-ZPQSTB411C"

format:
  html:
    theme: theme.scss
    link-external-newwindow: true

editor: visual

execute: 
  freeze: auto
