project:
  type: website

website:
  title: "Jolien Noels"
  site-url: "https://joliennoels.com"
  repo-url: "https://github.com/JolienNoels/joliennoels""
  favicon: assets/imgs/icon.png
  navbar:
    pinned: true
    right:
      - text: Research
        href: research/index.qmd  
      - text: Talks
        href: talks.qmd 
      - text: Articles
        href: articles.qmd 
  back-to-top-navigation: true
  
format:
  html:
    theme: theme.scss
    link-external-newwindow: true

editor: visual

execute: 
  freeze: auto
