---
sidebar: false
toc: false
page-layout: full
---

```{r build-table, include=FALSE}
library(gt)
library(tidyverse)

# Creating a data frame with the information
events_data <- tibble(
  Year = c(2024, 2024, 2024, 2024, 2024, 2024, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2022, 2022, 2021, 2021, 2021, 2020, 2020, 2020, 2020, 2020, 2019, 2019),
  Date = c(
    "Oct-17",
    "Oct-15",
    "June-20",
    "May-6",
    "Apr-4",
    "Mar-18",
    "Dec-14",
    "Nov-30",
    "Nov-23",
    "Oct-2",
    "Jul-20",
    "Jun-27",
    "Feb-22",
    "Oct-18",
    "Sep-12",
    "Nov-15",
    "Nov-12",
    "Sep-19 to Oct-13",
    "Nov-24",
    "Jun-5",
    "Mar-26",
    "Feb-13",
    "Jan-22",
    "Sep-30",
    "May-16"
  ),
  Event = c(
    "Sustainability Data EMEA 2024",
    "OECD Forum on Green Finance and Investment",
    "OECD-NGFS Workshop",
    "IFC Workshop on Addressing Climate Change Data Needs: The Global Debate and Central Banks' contribution",
    "Global Forum on the Environment and Climate Change",
    "17th Financial Risks International Forum",
    "Green Finance Research Advances",
    "CEFGroup Sustainable Finance and Accounting Symposium",
    "OECD COP28 Virtual Pavilion",
    "OECD Forum on Green Finance and Investment",
    "UNFCCC, First Workshop on Sharm El-Sheikh Dialogue on Article 2.1c of the Paris Agreement",
    "FFJ/Banque de France Workshop",
    "OECD Workshop",
    "European Securities and Markets Authority",
    "European Commission Workshop",
    "Just Transition Platform Meeting",
    "OECD COP26 Virtual Pavilion",
    "OECD workshop series",
    "Colombian Climate Assets Owners Disclosure Initiative virtual workshop",
    "J.P. Morgan Energy Transition virtual Road Show",
    "GRI Sustainable Finance lunch seminar, Grantham Research Institute",
    "Grantham Research Institute",
    "Colombian Climate Assets Owners Disclosure Initiative Conference",
    "LSE-BoE Climate Risk Workshop, Bank of England",
    "Presentation to ETION, London School of Economics"
  ),
  Title = c(
    "Exploring the impact of regulation on the ESG data landscape",
    "Aligning finance with climate policy goals: Is disclosure effective to inform robust assessments and drive decarbonisation?",
    "Workshop on Assessing the Climate Resilience of Finance",
    "Assessing the climate consistency of finance",
    "Empirical evidence on needs, sources, and actors for the NCQG",
    "Climate and systemic risks",
    "Climate change mitigation scenarios for financial sector target setting and alignment assessment",
    "Climate change mitigation scenarios for financial sector target setting and alignment assessment",
    "Scenarios for net zero: From global consistency to sectoral and geographical circumstances",
    "Aligning investment treaties with the Paris Agreement",
    "Assessing progress towards Article 2.1(c) of the Paris Agreement: Considerations relating to scope, approaches and metrics",
    "Climate change, natural disasters, and financial risk: how could central banks integrate environmental issues into their policies?",
    "Workshop on Metrics for Climate Transition and Net-Zero GHGs in Finance",
    "Working session on net-zero alignment of finance",
    "Workshop on regional industrial transitions to climate neutrality",
    "Launch of JTP Working Groups on carbon-intensive regions",
    "A place-based approach to climate policy",
    "OECD CFE R Training",
    "Understanding a company's strategy on managing climate risks based on disclosure",
    "Comparing European Oil & Gas decarbonization targets: challenges & insights from TPI briefing paper",
    "State of the Transition 2020",
    "Carbon Performance and Management Quality of Industrial and Material Sectors",
    "Assessing companies' preparedness for the low carbon transition",
    "Corporate disclosure and investor information on transition risk",
    "Transition progress to a carbon neutral world"
  ),
  Link = c(
    "https://www.environmental-finance.com/content/events/sustainability-data-emea/agenda.html",
    "https://www.oecd-events.org/oecd-forum-on-green-finance-and-investment-2024/session/209d7479-292a-ef11-86d2-000d3abd5c23",
    "https://www.oecd.org/environment/cc/workshoponassessingtheclimateresilienceoffinance-fromphysicalrisktoresiliencealignment.htm",
    "",
    "https://www.oecd.org/environment/cc/ccxg/globalforumontheenvironmentandclimatechange-april2024.htm",
    "https://www.risks-forum.org/",
    "https://green-finance-research-advances-2023.org/",
    "https://blogs.otago.ac.nz/cefg/events/cefgroup-sustainable-finance-and-accounting-symposium/",
    "https://www.oecd-events.org/cop28/session/2aafcfbd-7d67-ee11-9935-000d3a4605e4/scenarios-for-net-zero-from-global-consistency-to-sectoral-and-geographical-circumstances",
    "https://www.oecd-events.org/oecd-forum-on-green-finance-and-investment/session/a9056ac1-4c01-ee11-907a-002248859577",
    "https://unfccc.int/sites/default/files/resource/2023-07-20-workshop-pa-2.1c-oecd.pdf",
    "",
    "https://www.oecd.org/environment/cc/workshoponmetricsforclimatetransitionandnet-zeroghgsinfinance-supportingclimatepolicygoalsandavoidinggreenwashing.htm",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
  )
)

# Using htmltools to create hyperlinks
events_data <- events_data %>%
    mutate(
      Link2 = map2(Title, Link, ~ htmltools::a(href = .y, .x)),
      Link2 = map(Link2, ~ gt::html(as.character(.x))),
      Title2 = ifelse(
        Link == "",
        Title,
        Link2
      )
    )

# Creating a formatted table using gt
formatted_table <- events_data %>%
  select(Year, Date, Title2, Event) %>% 
  gt(groupname_col = 'Year') %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = Title2)
  ) %>% 
  tab_style(
    style = cell_text(color = "grey"),
    locations = cells_body(columns = Date)
  ) %>% 
  cols_align(
    align = "left",
    columns = everything()
  ) %>% 
  tab_options(column_labels.hidden = TRUE)

```

```{r show-table, echo=FALSE}
# Print the table
formatted_table

```
