---
title: "Assessing the climate consistency of finance"
subtitle: "Taking stock of methodologies and their links to climate mitigation policy objectives"
date: 2022-10-04
author:
  - name: Jolien Noels 
  - name: Raphaël Jachnik
categories: 
  - OECD
  - Sustainable Finance
Link: <a href='https://doi.org/10.1787/d12005e7-en'>Link</a>
---

[Link to the publication](https://www.oecd-ilibrary.org/environment/assessing-the-climate-consistency-of-finance_d12005e7-en)

## Abstract

This paper analyses existing methodologies developed by commercial services providers, research institutes or civil society organisations for investors and financial institutions, to assess the alignment of their assets and portfolios with the Paris Agreement temperature goal. The analysis is based on four main analytical dimensions - coverage of financial asset classes, choice of greenhouse gas performance metrics, selection of climate change mitigation scenarios, and approach for aggregating alignment assessment for a given asset class and at portfolio level. Within these dimensions, the analysis highlights that a range of different and complex methodological choices, as well as current scope and data limitations, impact the environmental integrity and policy relevance of alignment or misalignment results. The paper provides suggestions for improved and more comprehensive financial sector alignment assessment. These include the development of different complementary methodologies to cover a broader range of financial asset classes than the current main focus on listed corporate equity, the development of more tailored mitigation scenarios by climate policy and science communities, better communication of uncertainties by all stakeholders, and the need for a series of indicators to assess progress and impacts that include but are not limited to GHG based alignment assessments.
