---
title: "Paris-consistent climate change mitigation scenarios"
subtitle: "A framework for emissions pathway classification in line with global mitigation objectives"
date: 2023-09-28
author:
  - name: Coline Pouille
  - name: Marcia Rocha
  - name: Jolien Noels 
  - name: Raphaël Jachnik
categories: 
  - OECD
  - Net zero
Link: <a href='https://doi.org/10.1787/0de87ef8-en'>Link</a>
---

[Link to the publication]()

## Abstract

Since the adoption of the Paris Agreement, governments and economic actors have increasingly been setting greenhouse gas emissions reduction or net zero targets. Amidst risks of delayed action and greenwashing, there is need to understand whether climate related targets and transition plans are consistent with the Paris Agreement. Climate change mitigation scenarios can be used as inputs to design such targets and plans, and as benchmarks to assess progress towards them. In this context, this paper proposes criteria for selecting global climate change mitigation scenarios that can be considered consistent with the Paris Agreement temperature goal and emissions objectives, based on state-of-the-art literature on climate science and mitigation scenarios.
